apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-chart.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "base-chart.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
