example-app:

  annotations:
    branch: main
    commit: 1234abcd5678efgh90ijklmn
    deployedBy: user@example.com
    time: "2023-10-01T12:00:00Z"

  replicaCount: 3

  image:
    repository: docker.io/besqpin
    tag: "1.2.3"
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    annotations:
      azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: myapp.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - myapp.example.com
        secretName: myapp-tls

  env:
    - name: APP_ENV
      value: "production"
    - name: FEATURE_FLAG
      value: "true"

  configMap:
    enabled: true
    data:
      LOG_LEVEL: "info"
      API_URL: "https://api.example.com"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
