name: Publish My App Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: besqpin/helm-publish/.github/workflows/publish-helm.yaml@main
    with:
      chart-path: base-chart   # <-- change per app
      docker-org: besqpin        # <-- your Docker Hub org/user
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}