name: Publish My App Chart

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  versioning:
    needs: build
    uses: besqpin/workflow-library/.github/workflows/versioning.yml@main
    with:
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request.merged }}


  docker-publish:
    uses: besqpin/workflow-library/.github/workflows/docker-publish-helm.yaml@main
    with:
      chart-path: base-chart   # <-- change per app
      docker-org: besqpin        # <-- your Docker Hub org/user
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}


  ghcr-publish:
    uses: besqpin/workflow-library/.github/workflows/ghcr-publish-helm.yaml@main
    with:
      chart-path: base-chart
      ghcr-org: besqpin
      chart-name: base-chart
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}