name: Publish Helm Chart to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Debug folder structure
        run: |
          pwd
          ls -R base-chart

      - name: Extract version from Chart.yaml
        id: chart_version
        run: |
          VERSION=$(yq e '.version' base-chart/Chart.yaml)
          APP_VERSION=$(yq e '.appVersion' base-chart/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted chart version: $VERSION, appVersion: $APP_VERSION"

      - name: Package Helm chart
        run: |
          helm package base-chart \
            --version ${{ steps.chart_version.outputs.version }} \
            --app-version ${{ steps.chart_version.outputs.app_version }}
          ls -la

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | helm registry login registry-1.docker.io \
            -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Helm chart to Docker Hub
        run: |
          FILE=$(ls base-chart-*.tgz | head -n1)
          if [ -z "$FILE" ]; then
            echo "Error: No packaged chart found!"
            exit 1
          fi
          echo "Pushing $FILE to Docker Hub..."
          helm push $FILE oci://registry-1.docker.io/besqpin

