name: Publish My App Chart

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    uses: besqpin/workflow-library/.github/workflows/docker-publish-helm.yaml@main
    with:
      chart-path: base-chart   # <-- change per app
      docker-org: besqpin        # <-- your Docker Hub org/user
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}


  ghcr-publish:
    uses: besqpin/workflow-library/.github/workflows/ghcr-publish-helm.yml@main
    with:
      chart-path: base-chart
      ghcr-org: besqpin
      chart-name: base-chart
    secrets:
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}