name: Publish My App Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: besqpin/workflow-library/.github/workflows/publish-helm.yaml@main
    with:
      chart-path: base-chart   # <-- change per app
      docker-org: besqpin        # <-- your Docker Hub org/user
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  githubPublish:
    name: Push Helm Chart to Github
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4


      - name: Extract version from Chart.yaml
        id: chart_version
        run: |
          VERSION=$(yq e '.version' base-chart/Chart.yaml)
          APP_VERSION=$(yq e '.appVersion' base-chart/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT


      - name: Package Helm chart
        run: |
          helm package base-chart \
            --version ${{ steps.chart_version.outputs.version }} \
            --app-version ${{ steps.chart_version.outputs.app_version }}


      - name: Push Helm chart to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io \
            -u ${{ secrets.GHCR_USERNAME }} --password-stdin

          FILE=$(ls *.tgz | head -n1)
          if [ -z "$FILE" ]; then
            echo "Error: No packaged chart found!"
            exit 1
          fi
          echo "Pushing $FILE to GitHub Container Registry..."
          helm push $FILE oci://ghcr.io/besqpin/helm-base