name: Publish Helm Chart

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # Needed for pushing to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4   # pick your preferred version

      - name: Extract chart version from chart.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' base-chart/Chart.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: |
          pwd
          ls -la
          helm package base-chart --version ${{ steps.version.outputs.version }} --app-version ${{ steps.version.outputs.version }}

      - name: Log in to GHCR
        run: |
          echo "${{ github.token }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR
        run: |
          helm push base-chart-${{ steps.version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
